pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven { url "https://maven.shedaniel.me/" } // ГЛАВНЫЙ СКЛАД ДЛЯ CLOTH CONFIG
        maven { url "https://maven.terraformersmc.com/" }
        maven { url "https://libraries.minecraft.net/" }
    }
}

rootProject.name = 'Lunaire'
