name: Lunaire Build Fix
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Mod
        run: |
          # Пытаемся найти папку, где лежит проект
          if [ -f "build.gradle" ]; then
            PROJECT_DIR="."
          elif [ -f "Lunaire/build.gradle" ]; then
            PROJECT_DIR="Lunaire"
          else
            echo "ОШИБКА: Файл build.gradle не найден ни в корне, ни в папке Lunaire!"
            exit 1
          fi
          
          echo "Проект найден в: $PROJECT_DIR"
          cd $PROJECT_DIR
          chmod +x gradlew
          ./gradlew build --no-daemon
